# Generated by Django 3.2 on 2021-05-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210502_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
