# Generated by Django 3.2 on 2021-05-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membership_type_member'),
        ('videos', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='allowed_memberships',
            field=models.ManyToManyField(related_name='allowed_memberships', to='membership.Membership'),
        ),
    ]
