# Generated by Django 3.2 on 2021-05-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20210502_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type_member',
            field=models.CharField(choices=[('Free', 'free'), ('Professional', 'pro')], default='Free', max_length=50),
        ),
    ]
