# Generated by Django 3.2 on 2021-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.CharField(blank=True, max_length=254, primary_key=True, serialize=False),
        ),
    ]
