# Generated by Django 3.2.2 on 2021-05-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20210503_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
