# Generated by Django 3.2.2 on 2021-05-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210503_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
