# Generated by Django 3.2.2 on 2021-05-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
